# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7vx485tffg1157-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Code/Vivado/VerilogHDLExercise/module/module.cache/wt [current_project]
set_property parent.project_path D:/Code/Vivado/VerilogHDLExercise/module/module.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Code/Vivado/VerilogHDLExercise/module/module.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/Code/Vivado/VerilogHDLExercise/module/module.srcs/sources_1/new/SR_latch.v
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top SR_latch -part xc7vx485tffg1157-1


write_checkpoint -force -noxdef SR_latch.dcp

catch { report_utilization -file SR_latch_utilization_synth.rpt -pb SR_latch_utilization_synth.pb }
